### PR TITLE
New pull request

### PR DESCRIPTION
**Pull request by raul-rufato**

### CODE REVIEW

**Comment by Paul-Saves** [comment]
Thanks you for the quick update ! 
However, the file is the wrong one

Better to use that one : (the same as in colab)
[VTF_properties.json.txt](https://github.com/SMTorg/smt/files/8606306/VTF_properties.json.txt)

**Comment by raul-rufato** [comment]
> Thanks you for the quick update ! However, the file is the wrong one
> 
> Better to use that one : (the same as in colab) [VTF_properties.json.txt](https://github.com/SMTorg/smt/files/8606306/VTF_properties.json.txt)

Hello! The colab is calling a .csv file from google drive (not .json.txt). If you think it is better, I can put directly the .csv file on ..smt/tutorial

**Comment by relf** [comment]
Hi, I will merge this PR in the end but @raul-rufato you should strive to make meaningful title, description or [commit messages](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/). Reading this PR, I am unable to tell anything about its content.

**Comment by Paul-Saves** [comment]
> > Thanks you for the quick update ! However, the file is the wrong one
> > Better to use that one : (the same as in colab) [VTF_properties.json.txt](https://github.com/SMTorg/smt/files/8606306/VTF_properties.json.txt)
> 
> Hello! The colab is calling a .csv file from google drive (not .json.txt). If you think it is better, I can put directly the .csv file on ..smt/tutorial

Yes please (I added the .txt at the end but it would be better to use a csv than a json)

**Comment by relf** [comment]
Closing as duplicate of #357

**Pull request closed without merging**
