### PR TITLE
Gower distance based mixed kernel

### PR DESCRIPTION
**Pull request by raul-rufato**
I am trying to implement the Gower distance to calculate the mixed kernel between categorical and continuous variables.

### CODE REVIEW

**Comment by Paul-Saves** [comment]
Ok, the code seems clean to me but, can you add examples and run the tutorial. 
The notebook is https://github.com/SMTorg/smt/blob/master/tutorial/SMT_MixedInteger_application.ipynb and should be updated.
Thanks a lot for your code contribution !

**Comment by raul-rufato** [comment]
Hi Paul

Yes I can do it

**Comment by relf** [comment]
Hi Raul. Thanks for your contribution. Do you plan to change something else? 

Looking at your commit messages, I have the feeling you are using the Github interface directly to make changes. May I suggest you learn about [git command line](https://git-scm.com/docs/gittutorial) and [how to contribute to a Github project](https://www.dataschool.io/how-to-contribute-on-github/), it will be easier for you for further open source contributions.

**Comment by raul-rufato** [comment]
Hi Mr. Lafage, 

I don't want to change anything else.  
Thanks for your advices!

**Comment by relf** [comment]
Ok, I am going to refactor a bit before merging...

**Comment by Paul-Saves** [comment]
The documentation should be updated

**Comment by relf** [comment]
Definitely, PR welcomed! Beside I prefer to make separate PRs dedicated to documentation to avoid cluttering "code PR" (doc PRs unfortunately tend to include numerous changes due to the production toolchain).

**Pull request merged**
