### PR TITLE
Adding a tutorial for a mixed surrogate model in a hybrid composites problem

### PR DESCRIPTION
**Pull request by raul-rufato**
I am adding a tutorial, which references an upcoming article: A mixed-categorical data-drive method for prediction and optimization of hybrid discontinuous composites. It was during this work that the Gower distance was implemented in SMT. The tutorial builds a surrogate model to predict the properties of hybrid composites.

### CODE REVIEW

**Comment by relf** [comment]
@raul-rufato, thanks for improving your PR description. I guess you are using Github to add/delete files but the proper way is to add/update your files locally then update your branch by pushing. I recommend you take a look at tutorials like [this one](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners) to learn basics about `git`, Github and how to handle PRs.

**Comment by Paul-Saves** [comment]
You have to modify the read and import 

```
try :
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials

    # 1. Authenticate and create the PyDrive client.
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    json_import = drive.CreateFile({'id':'1fcB39mktJ2npTNqrF8dgZa7PWh3wU55X'})
    json_import.GetContentFile('VTF_properties.json')
except :
    **df = pd.read_csv(open('VTF_properties.csv'))**
```

**Comment by raul-rufato** [comment]
In the case of launching the notebook in Colab, replacing the line **df = pd.read_csv(open('VTF_properties.json'))**  with **df = pd.read_csv(open('VTF_properties.csv'))** does not work.  The .GetContentFile reads a .json file, then you need the line **df = pd.read_csv(open('VTF_properties.json'))**.

The way it runs correctly both on Colab and Jupyter is the following:

(try+ df = pd.read_csv(open('VTF_properties.json'))): Colab
(except) : Jupyter

```
try :
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials

    # 1. Authenticate and create the PyDrive client.
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    json_import = drive.CreateFile({'id':'1fcB39mktJ2npTNqrF8dgZa7PWh3wU55X'})
    json_import.GetContentFile('VTF_properties.json')
except :
    df = pd.read_csv(open('VTF_properties.csv'))

df = pd.read_csv(open('VTF_properties.json'))
```

**Comment by Paul-Saves** [comment]
ok but put the: df = pd.read_csv(open('VTF_properties.json')) at the end of the try ! 

Like this: 
```
try :
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials

    # 1. Authenticate and create the PyDrive client.
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    json_import = drive.CreateFile({'id':'1fcB39mktJ2npTNqrF8dgZa7PWh3wU55X'})
    json_import.GetContentFile('VTF_properties.json')
    df = pd.read_csv(open('VTF_properties.json'))
except :
    df = pd.read_csv(open('VTF_properties.csv'))
```

**Comment by Paul-Saves** [comment]
That's good to me @relf  ! :)

**Pull request merged**
