### PR TITLE
New smt

### PR DESCRIPTION
**Pull request by raul-rufato**
I am adding an example in the tutorials for surrogate models of mixed variables that uses the Gower correlation kernel for hybrid discontinous composites.

### CODE REVIEW

**Comment by Paul-Saves** [comment]
I'm a bit in a rush, right now.  I changed Gower distance a lot lately, I'll see later, if you're not in a hurry.

**Comment by raul-rufato** [comment]
Hello Paul,

It is ok, I am not in a hurry. I’ve changed nothing in the .py files. I’ve just added an example in the tutorials notebook as I will publish a paper on it.

De: Saves ***@***.***>
Enviado:27 April 2022 14:18
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [SMTorg/smt] New smt (PR #354)


I'm a bit in a rush, right now. I changed Gower distance a lot lately, I'll see later, if you're not in a hurry.

**Comment by Paul-Saves** [comment]
Hey ! 
So, your test is adapted for Colab, not PC.

Here is the work around : 

!pip install -U -q PyDrive

`try :
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials

    # 1. Authenticate and create the PyDrive client.
    #auth.authenticate_user()
    gauth = GoogleAuth()
    #gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    json_import = drive.CreateFile({'id':'1fcB39mktJ2npTNqrF8dgZa7PWh3wU55X'})
    json_import.GetContentFile('VTF_properties.json')
except :
    df = pd.read_csv(open('VTF_properties.json'))
`

- [ ] Please modify the notebook 
- [ ] Add VTF_properties.json in ~/smt/tutorial

The json file is easy to have, I could send it to you by mail, if you want.

Paul

**Review by Paul-Saves — CHANGES_REQUESTED** [review]
See the comment ^

**Pull request closed without merging**
