### PR TITLE
 Implement hierarchical variables 

### LINKED ISSUE #405: Problem with EGO and ORD variables
test_ego_mixed_integer do not work. 
There is a problem of specification that just appeared within EGO with ORD variables.

### PR DESCRIPTION
**Pull request by Paul-Saves**
First implementation of hierarchical variables. There is some stuff to be implemented yet but this PR introduces most concepts used for that new "kind" of variables.

Also fix #405, it was a check issue in a given line of EGO, nothing really problematic.

### CODE REVIEW

**Comment by Paul-Saves** [comment]
Current limitations and ideas for future improvements:
- The hierarchical meta variable was not tested not implemented in this PR, it should not be too hard to implement in future works.
- Continuous Relaxation+Hierarchical variables was not tested in this work. Neither was tested what happened without categorical variables. 
- Hierarchical variables for non-Kriging models was not investigated. Maybe a warning should do.
- Sampling methods for hierarchical variables was not worked on. It could be a way for further research works.
-

**Comment by Paul-Saves** [comment]
@relf I have done the required improvements for this PR, tell me if it is okay for you !

**Review by relf — CHANGES_REQUESTED** [review]
Thanks Paul! My remarks are meant to improve the understanding of the implementation for further maintainance (to help your future you and/or me 😅 ). 
It would be interesting to comment algorithms main steps and/or reference algorithms in existing papers if possible.

**Comment by Paul-Saves** [comment]
I also added the method expand_lhs (@rconde1997) for mixed integer variables.

**Review by relf — APPROVED** [review]

**Pull request merged**
