### PR TITLE
Multi-sample variant of EGO

### PR DESCRIPTION
**Pull request by rruusu**
The EGO application is fixed for issue #189 and a new variant of EGO in ego_ms.py has been added.

This new variant is able to evaluate multiple samples of the objective function simultaneously by temporarily updating the surrogate model with worst-case estimates until the real objective values are acquired.

Below is a sample using the UCB criterion, with 4 new samples generated per iteration.

EGO_ms

### CODE REVIEW

**Comment by rruusu** [comment]
Script for generating the sample:

```python
import numpy as np
import six
from smt.applications import EGO_MS
from smt.sampling_methods import FullFactorial

import sklearn
import matplotlib.pyplot as plt
from matplotlib import colors
from mpl_toolkits.mplot3d import Axes3D
from scipy.stats import norm

def function_test_1d(x):
    # function xsinx
    import numpy as np

    x = np.reshape(x, (-1,))
    y = np.zeros(x.shape)
    y = (x - 3.5) * np.sin((x - 3.5) / (np.pi))
    return y.reshape((-1, 1))

n_iter = 4
n_sample = 4
xlimits = np.array([[0.0, 25.0]])
xdoe = np.atleast_2d([0, 7, 25]).T
n_doe = xdoe.size

criterion = "UCB"  #'EI' or 'SBO' or 'UCB'

ego = EGO_MS(n_iter=n_iter, n_sample=n_sample, criterion=criterion, xdoe=xdoe, xlimits=xlimits)

x_opt, y_opt, ind_best, x_data, y_data, x_doe, y_doe = ego.optimize(
    fun=function_test_1d
)
print("Minimum in x={:.4f} with f(x)={:.4f}".format(float(x_opt), float(y_opt)))

x_plot = np.atleast_2d(np.linspace(0, 25, 100)).T
y_plot = function_test_1d(x_plot)

print("Sample values: x={}".format(x_data))

fig = plt.figure(figsize=[10, 10])
for i in range(n_iter):
    k = n_doe + i*n_sample
    x_data_k = x_data[0:k]
    y_data_k = y_data[0:k]
    ego.gpr.set_training_values(x_data_k, y_data_k)
    ego.gpr.train()

    y_gp_plot = ego.gpr.predict_values(x_plot)
    y_gp_plot_var = ego.gpr.predict_variances(x_plot)
    y_ei_plot = -ego.EI(x_plot, y_data_k)

    ax = fig.add_subplot((n_iter + 1) // 2, 2, i + 1)
    ax1 = ax.twinx()
    #ei, = ax1.plot(x_plot, y_ei_plot, color="red")

    true_fun, = ax.plot(x_plot, y_plot)
    data, = ax.plot(
        x_data_k, y_data_k, linestyle="", marker="o", color="orange"
    )
    opt, = ax.plot(
        x_data[k:k+n_sample], y_data[k:k+n_sample], linestyle="", marker="*", color="r"
    )
    gp, = ax.plot(x_plot, y_gp_plot, linestyle="--", color="g")
    sig_plus = y_gp_plot + 3 * np.sqrt(y_gp_plot_var)
    sig_moins = y_gp_plot - 3 * np.sqrt(y_gp_plot_var)
    un_gp = ax.fill_between(
        x_plot.T[0], sig_plus.T[0], sig_moins.T[0], alpha=0.3, color="g"
    )
    lines = [true_fun, data, gp, un_gp, opt]#, ei]
    fig.suptitle("EGO optimization of $f(x) = x \sin{x}$")
    fig.subplots_adjust(hspace=0.4, wspace=0.4, top=0.8)
    ax.set_title("iteration {}".format(i + 1))
    fig.legend(
        lines,
        [
            "f(x)=xsin(x)",
            "Given data points",
            "Kriging prediction",
            "Kriging 99% confidence interval",
            "Next point to evaluate",
            #"Expected improvment function",
        ],
    )
plt.show()
```

**Comment by relf** [comment]
Thank you for your contribution, I will pull your fix for #189 and deal with EGO_MS later on.

**Comment by rruusu** [comment]
Note: The fix for #189 seems to break test_branin_2d(), but it turns out to be caused by a random fluke that allowed the earlier version to reach the given criterion within 10 iterations.

image

image

**Comment by relf** [comment]
As I understand you've implemented q-EI approximation. Do you have any paper reference?

**Comment by relf** [comment]
The fix for #189 was done in #192, I rename this issue to focus on the enhancement proposal.

**Comment by relf** [comment]
Thanks for your contribution. Multi-sample EGO is implemented with PR #202

**Pull request closed without merging**
